namespace Smart.Design.Library.TagHelpers.Icon;

/// <summary>
/// Supported icons by Smart design.
/// We added <see cref="None"/> value by default to prevent having to set nullable icon attributes.
/// </summary>
public enum Image
{
    None = 0,
    Add,
    Archive,
    ArrowDown,
    ArrowLeft,
    ArrowLeftUp,
    ArrowLeftDown,
    ArrowRight,
    ArrowRightUp,
    ArrowRightDown,
    ArrowUp,
    Attachment,
    BarChartAlt,
    BarChart,
    Bills,
    Calendar,
    Call,
    CaretDown,
    CaretLeftRight,
    CaretLeft,
    CaretRight,
    CaretUpDown,
    CaretUp,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircleAdd,
    CircleCheck,
    CircleError,
    CircleHelp,
    CircleInformation,
    CirclePercent,
    ClipboardList,
    Clock,
    Close,
    ContactBook,
    Copy,
    Delete,
    DocumentEmpty,
    DocumentMissing,
    Document,
    Download,
    EditAlt,
    Edit,
    Email,
    ExternalLink,
    EyeOff,
    Eye,
    Facebook,
    Favorite,
    Filter,
    Github,
    Home,
    Instagram,
    Link,
    Location,
    Menu,
    Message,
    OptionsHorizontal,
    Package,
    Pen,
    Percent,
    Print,
    Remove,
    Save,
    Search,
    Send,
    Settings,
    SignOut,
    Table,
    Tag,
    ThreeRows,
    Timer,
    Twitter,
    User,
    Users,
    Warning
}
